version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
  settings:
    errcheck:
      check-type-assertions: false
      exclude-functions:
        - (database/sql.Rows).Close
        - (database/sql.Stmt).Close
        - (*github.com/nagyonmarci/ossf-scout.Rows).Close
  exclusions:
    rules:
      - path: _test\.go
        linters: [errcheck]
