package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// ── Template report (static snapshot, no AI) ──────────────────────────────────

func generateTemplateReport(ctx *auditContext) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Security Data Snapshot: %s", ctx.Meta.Repo)
	w("")
	w("**Date:** %s | **Commit:** %s | **Mode:** Static analysis only (no AI synthesis)", ctx.Meta.Date[:10], ctx.Meta.Ref)
	w("")
	w("---")
	w("")
	w("## CI/CD")
	w("")
	w("### Unpinned GitHub Actions (`uses: action@vX` tags)")
	w("")
	w("```")
	w("%s", ctx.CICD.UnpinnedActions)
	w("```")
	w("")
	w("### Actionlint")
	w("")
	w("```")
	w("%s", ctx.CICD.Actionlint)
	w("```")
	w("")
	w("### Workflow files")
	w("")
	w("```")
	w("%s", ctx.CICD.WorkflowList)
	w("```")
	w("")
	w("### Zizmor analysis")
	w("")
	w("```")
	w("%s", ctx.CICD.Zizmor)
	w("```")
	w("")
	w("### Security workflow contents (codeql / trivy / scorecard triggers)")
	w("")
	w("```yaml")
	w("%s", ctx.CICD.WorkflowContents)
	w("```")
	w("")
	w("---")
	w("")
	w("## Code Patterns")
	w("")
	w("### eval() usage")
	w("")
	w("```")
	w("%s", ctx.Code.EvalUsage)
	w("```")
	w("")
	w("### Math.random() usage")
	w("")
	w("```")
	w("%s", ctx.Code.MathRandom)
	w("```")
	w("")
	w("### Raw SQL calls")
	w("")
	w("```")
	w("%s", ctx.Code.RawSqlCalls)
	w("```")
	w("")
	w("### X-Powered-By header exposure")
	w("")
	w("```")
	w("%s", ctx.Code.XPoweredByHeader)
	w("```")
	w("")
	w("### Hardcoded secret hints")
	w("")
	w("```")
	w("%s", ctx.Code.HardcodedSecretHints)
	w("```")
	w("")
	w("### Weak crypto (MD5/SHA1)")
	w("")
	w("```")
	w("%s", ctx.Code.WeakCrypto)
	w("```")
	w("")
	w("### process.exit / os.Exit calls")
	w("")
	w("```")
	w("%s", ctx.Code.ProcessExitCalls)
	w("```")
	w("")
	w("### SQL injection patterns")
	w("")
	w("```")
	w("%s", ctx.Code.SqlInjection)
	w("```")
	w("")
	w("### SSRF (fetch / axios / got)")
	w("")
	w("```")
	w("%s", ctx.Code.SSRF)
	w("```")
	w("")
	w("### Path traversal (readFile / path.join)")
	w("")
	w("```")
	w("%s", ctx.Code.PathTraversal)
	w("```")
	w("")
	w("### XXE (xml2js / DOMParser)")
	w("")
	w("```")
	w("%s", ctx.Code.XXE)
	w("```")
	w("")
	w("### Deserialization (yaml.load / JSON.parse)")
	w("")
	w("```")
	w("%s", ctx.Code.Deserialization)
	w("```")
	w("")
	w("### Rate limiting")
	w("")
	w("```")
	w("%s", ctx.Code.RateLimiting)
	w("```")
	w("")
	w("### CORS config")
	w("")
	w("```")
	w("%s", ctx.Code.CORSConfig)
	w("```")
	w("")
	w("---")
	w("")
	w("## Key Security Files")
	w("")
	w("### Entry point")
	w("")
	w("```typescript")
	w("%s", ctx.KeyFiles.EntryPoint)
	w("```")
	w("")
	w("### Auth middleware")
	w("")
	w("```typescript")
	w("%s", ctx.KeyFiles.AuthMiddleware)
	w("```")
	w("")
	w("### Permission system")
	w("")
	w("```typescript")
	w("%s", ctx.KeyFiles.PermissionSystem)
	w("```")
	w("")
	w("### Security config (helmet / cors / session)")
	w("")
	w("```")
	w("%s", ctx.KeyFiles.SecurityConfig)
	w("```")
	w("")
	w("### Startup validation (SECRET / env enforcement)")
	w("")
	w("```typescript")
	w("%s", ctx.KeyFiles.StartupValidation)
	w("```")
	w("")
	w("### Error handler")
	w("")
	w("```typescript")
	w("%s", ctx.KeyFiles.ErrorHandler)
	w("```")
	w("")
	w("### Helmet config")
	w("")
	w("```typescript")
	w("%s", ctx.KeyFiles.HelmetConfig)
	w("```")
	w("")
	w("---")
	w("")
	w("## Infrastructure")
	w("")
	w("### Dockerfile")
	w("")
	w("```dockerfile")
	w("%s", ctx.Infra.Dockerfile)
	w("```")
	w("")
	w("### Helm lint")
	w("")
	w("```")
	w("%s", ctx.Infra.HelmLint)
	w("```")
	w("")
	w("### Helm secret template")
	w("")
	w("```yaml")
	w("%s", ctx.Infra.HelmSecretTemplate)
	w("```")
	w("")
	w("### Helm values")
	w("")
	w("```yaml")
	w("%s", ctx.Infra.HelmValues)
	w("```")
	w("")
	w("---")
	w("")
	w("## Dependencies")
	w("")
	w("### pnpm / npm audit")
	w("")
	w("```")
	w("%s", ctx.Dependencies.PnpmAudit)
	w("```")
	w("")
	w("### Workspace overrides")
	w("")
	w("```")
	w("%s", ctx.Dependencies.WorkspaceOverrides)
	w("```")
	w("")
	w("---")
	w("")
	w("## Git History")
	w("")
	w("### Recent commits")
	w("")
	w("```")
	w("%s", ctx.Git.RecentCommits)
	w("```")
	w("")
	w("### Recently changed files (last 10 commits)")
	w("")
	w("```")
	w("%s", ctx.Git.RecentlyChangedFiles)
	w("```")
	w("")
	w("---")
	w("")
	w("## GitHub")
	w("")

	if issues, ok := ctx.GitHub.OpenIssues.([]interface{}); ok {
		w("**Open issues:** %d", len(issues))
	} else {
		w("**Open issues:** (unavailable)")
	}

	if prs, ok := ctx.GitHub.OpenPRs.([]interface{}); ok {
		w("**Open PRs:** %d", len(prs))
	} else {
		w("**Open PRs:** (unavailable)")
	}

	w("")
	w("### Secret-scanning alerts")
	w("")
	w("```")
	w("%s", ctx.GitHub.SecurityAlerts)
	w("```")
	w("")
	w("### Branch protection (main)")
	w("")
	w("```json")
	w("%s", ctx.GitHub.BranchProtection)
	w("```")
	w("")
	w("---")
	w("")
	w("## Secrets Scanning")
	w("")
	w("### Gitleaks")
	w("")
	w("```")
	w("%s", ctx.Secrets.Gitleaks)
	w("```")
	w("")
	w("### TruffleHog")
	w("")
	w("```")
	w("%s", ctx.Secrets.TruffleHog)
	w("```")
	w("")
	w("### Private key headers")
	w("")
	w("```")
	w("%s", ctx.Secrets.PrivateKeyHeaders)
	w("```")
	w("")
	w("### .env files")
	w("")
	w("```")
	w("%s", ctx.Secrets.EnvFiles)
	w("```")
	w("")
	w("### Token patterns (AWS/JWT/GH)")
	w("")
	w("```")
	w("%s", ctx.Secrets.TokenPatterns)
	w("```")
	w("")
	w("---")
	w("")
	w("## Infrastructure as Code (IaC)")
	w("")
	w("### Terraform files")
	w("")
	w("```")
	w("%s", ctx.IaC.TerraformFiles)
	w("```")
	w("")
	w("### Checkov")
	w("")
	w("```")
	w("%s", ctx.IaC.Checkov)
	w("```")
	w("")
	w("### Trivy config")
	w("")
	w("```")
	w("%s", ctx.IaC.Trivy)
	w("```")
	w("")
	w("### Kubernetes manifests")
	w("")
	w("```")
	w("%s", ctx.IaC.KubeManifests)
	w("```")
	w("")
	w("### kube-linter")
	w("")
	w("```")
	w("%s", ctx.IaC.KubeLinter)
	w("```")
	w("")
	w("---")
	w("")
	w("## Policy as Code")
	w("")
	w("### OPA (.rego files)")
	w("")
	w("```")
	w("%s", ctx.Policy.OPAFiles)
	w("```")
	w("")
	w("### Kyverno policies")
	w("")
	w("```")
	w("%s", ctx.Policy.KyvernoFiles)
	w("```")
	w("")
	w("### Falco rules")
	w("")
	w("```")
	w("%s", ctx.Policy.FalcoRules)
	w("```")
	w("")
	w("---")
	w("")
	w("## SLSA / Supply Chain")
	w("")
	w("### Provenance files")
	w("")
	w("```")
	w("%s", ctx.SLSA.ProvenanceFiles)
	w("```")
	w("")
	w("### SBOM files")
	w("")
	w("```")
	w("%s", ctx.SLSA.SBOMFiles)
	w("```")
	w("")
	w("### Cosign / signing keys")
	w("")
	w("```")
	w("%s", ctx.SLSA.CosignFiles)
	w("```")
	w("")
	w("### SLSA / attestation workflow usage")
	w("")
	w("```")
	w("%s", ctx.SLSA.SLSAWorkflow)
	w("```")
	w("")
	w("### Signed commit (latest)")
	w("")
	w("```")
	w("%s", ctx.SLSA.SignedCommit)
	w("```")

	return b.String()
}

// ── Audit orchestration ─────────────────────────────────────────────────────

// ── Runner ────────────────────────────────────────────────────────────────────

func runAudit(db *sql.DB, id, repo, ghToken, provider, anthropicKey, ollamaURL, model, analysisModel string, splitGeneration bool) {
	_ = dbUpdateAuditRunning(db, id)

	auditCtx, tmpDir, err := collectContext(repo, ghToken)
	if err != nil {
		_ = dbUpdateAuditError(db, id, fmt.Sprintf("collect failed: %v", err))
		return
	}
	defer os.RemoveAll(tmpDir) //nolint:errcheck

	if raw, merr := json.Marshal(auditCtx); merr == nil {
		_ = dbUpdateAuditContext(db, id, string(raw))
	}

	runAuditGenerate(db, id, auditCtx, provider, anthropicKey, ollamaURL, model, analysisModel, splitGeneration)
}

func runAuditFromContext(db *sql.DB, id, contextJSON, provider, anthropicKey, ollamaURL, model, analysisModel string, splitGeneration bool) {
	var auditCtx auditContext
	if err := json.Unmarshal([]byte(contextJSON), &auditCtx); err != nil {
		_ = dbUpdateAuditError(db, id, "context unmarshal failed: "+err.Error())
		return
	}
	runAuditGenerate(db, id, &auditCtx, provider, anthropicKey, ollamaURL, model, analysisModel, splitGeneration)
}

func runAuditGenerate(db *sql.DB, id string, auditCtx *auditContext, provider, anthropicKey, ollamaURL, model, analysisModel string, splitGeneration bool) {
	var report string
	var inputTokens, outputTokens int
	var err error

	switch provider {
	case "anthropic":
		if splitGeneration {
			report, inputTokens, outputTokens, err = generateSplitClaudeReport(auditCtx, anthropicKey, analysisModel, model)
		} else {
			report, inputTokens, outputTokens, err = generateReport(auditCtx, anthropicKey, model)
		}
	case "ollama":
		if splitGeneration {
			report, inputTokens, outputTokens, err = generateSplitOllamaReport(auditCtx, ollamaURL, analysisModel, model)
		} else {
			report, inputTokens, outputTokens, err = generateOllamaReport(auditCtx, ollamaURL, model)
		}
	default:
		_ = dbUpdateAuditDone(db, id, generateTemplateReport(auditCtx), 0, 0)
		return
	}

	if err != nil {
		// Save the static snapshot as fallback so the user has downloadable data
		_ = dbUpdateAuditErrorWithReport(db, id,
			fmt.Sprintf("generate failed: %v", err),
			generateTemplateReport(auditCtx))
		return
	}
	// Ground every concrete claim against the collected evidence before saving.
	report = verifyReport(report, auditCtx)
	_ = dbUpdateAuditDone(db, id, report, inputTokens, outputTokens)
}
